source 'https://github.com/cocoapods/specs.git'

platform :ios, '7.0'

target :SSDynamicTextExample do
  pod 'SSDynamicText', path: '..'

  target :SSDynamicTextTests do
    inherit! :search_paths
    pod 'OCMock', '~> 3'
  end
end
