source 'https://github.com/cocoapods/specs.git'

platform :ios, '7.0'

xcodeproj 'SSDynamicTextExample'

pod 'SSDynamicText', :path => '../SSDynamicText.podspec'

target :SSDynamicTextTests, :exclusive => true do
    pod 'Expecta'
end
