source 'https://github.com/cocoapods/specs.git'

platform :ios, '7.0'

xcodeproj 'SSDynamicTextExample'

def install_pods
    pod 'SSDynamicText', :path => '../SSDynamicText.podspec'
end

target :SSDynamicTextExample do
    install_pods
end

target :SSDynamicTextTests, :exclusive => true do
    install_pods
    pod 'OCMock', '~> 3'
end
