#!/bin/sh

export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

set -o pipefail && xcodebuild \
-workspace Example/SSDynamicTextExample.xcworkspace \
-scheme SSDynamicTextExample \
-sdk iphonesimulator \
clean build \
ONLY_ACTIVE_ARCH=NO \
RUN_CLANG_STATIC_ANALYZER=YES \
CLANG_STATIC_ANALYZER_MODE=deep | xcpretty -c
